# Generated by Django 3.1.5 on 2021-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='country',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_country', to='manager.Country'),
        ),
    ]
