# Generated by Django 3.1.5 on 2021-01-27 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210127_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='country',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_country', to='manager.country'),
        ),
    ]
