# Generated by Django 3.1.5 on 2021-01-27 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20210127_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название события')),
                ('date_start', models.DateTimeField(verbose_name='Время начало события')),
                ('date_stop', models.DateTimeField(blank=True, null=True, verbose_name='Время окончание события')),
                ('reminder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_user', to='manager.remindertime', verbose_name='Когда напомнить')),
                ('user_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='кто создал событие')),
            ],
        ),
    ]
