# Generated by Django 3.1.5 on 2021-01-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_createevent_remindertime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createevent',
            old_name='date_stop',
            new_name='date_finish',
        ),
    ]
