# Generated by Django 3.1.5 on 2021-01-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20210129_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidays',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Праздник'),
        ),
    ]
