# Generated by Django 3.1.5 on 2021-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20210129_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='need_remind',
            field=models.BooleanField(default=False, verbose_name='Оповещение'),
        ),
        migrations.AlterField(
            model_name='createevent',
            name='reminder',
            field=models.DurationField(blank=True, choices=[(1, 'За час'), (2, 'За 2 часа'), (4, 'За 4 часа'), (24, 'За день'), (168, 'За неделю')], null=True, verbose_name='Когда напомнить'),
        ),
    ]
