# Generated by Django 3.1.5 on 2021-01-31 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_auto_20210131_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createevent',
            old_name='need_remind',
            new_name='notification',
        ),
        migrations.AlterField(
            model_name='createevent',
            name='reminder',
            field=models.DurationField(blank=True, choices=[(datetime.timedelta(seconds=3600), 'За час'), (datetime.timedelta(seconds=7200), 'За 2 часа'), (datetime.timedelta(seconds=14400), 'За 4 часа'), (datetime.timedelta(days=1), 'За день'), (datetime.timedelta(days=7), 'За неделю')], null=True, verbose_name='Когда напомнить'),
        ),
    ]
